### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by vlaben** [Sandbird/Dayz.Epoch.1062.3d.Editor.Hive.Mission#2]
Hello, @Sandbird ,
as always, well done!
iben

**Comment by Sandbird** [comment]
hehe thanks man :)

**Comment by vlaben** [comment]
Keep it on. If you need second pair of eyes on extDB3, let me know... really love your work

**Comment by Sandbird** [comment]
If you know how to fix extDB3 sometimes crapping on me and returning objects in arrays and in quotes also .... that would be helpful. For example: https://github.com/Sandbird/Dayz.Epoch.1062.3d.Editor.Hive.Mission/blob/fa4dcfb3132c9ecd1e3d5649f664fe6a0f6bd341/missions/3d.live1062.DayzEpochTemplate.Chernarus/dayz_server/compile/server_publishVehicle.sqf#L57
sometimes things come back like this: "[blahblah]" when it should be [blahblah] so i have to resort to things like str_replace functions and then compile the result to create it into an arma array.
Arma2Net wasnt doing that....extdb3 is so much different...It likes predefined queries not async calls that much.

**Comment by vlaben** [comment]
I will check my old updated repo (that one you use from AirMan). I've never had any issue with returning strings when I don't need them. But it's important to see how you compose strings and calls first. I will return back to you soon... just give me some time (job is a bitch :))

**Comment by vlaben** [comment]
I'm so sorry for very late response.
As promised, I've looked into your problem and here are my thoughts:

Let's take an example from [server_publishVehicle.sqf#L55](https://github.com/Sandbird/Dayz.Epoch.1062.3d.Editor.Hive.Mission/blob/master/missions/3d.live1062.DayzEpochTemplate.Chernarus/dayz_server/compile/server_publishVehicle.sqf#L55 "Go to link"):
Here we can see the problem, as you described above:

> sometimes things come back like this: "[blahblah]" when it should be [blahblah] so i have to resort to things like str_replace functions and then compile the result to create it into an arma array.

The reason, why it's happening (using 1 specific case in your codebase):
1. Function `server_hiveReadWriteLarge` is called (similar functions with the same problem are eg. `server_hiveWrite`, `server_hiveWriteAndWait`).
2. These functions are calling function [extDB_async](https://github.com/Sandbird/Dayz.Epoch.1062.3d.Editor.Hive.Mission/blob/master/missions/3d.live1062.DayzEpochTemplate.Chernarus/dayz_server/extDB/custom/asyncCall.sqf "Go to link"), which has commented out important part of original code:
`//_queryResult = call compile _queryResult;` (line 74).
3. Because `queryResult` string is not compiled, value is wrapped inside double quotes - hence the described issue.

Fix is actually easy - uncomment line 74 (see above) and you will be good.

The reason, why it probably sometimes worked and sometimes not - some of the functions or direct code handling async extdb api call correctly compiled result - hence without extra quotes.

Cheers.

**Comment by Sandbird** [comment]
Thanks for getting to the bottom of this.. I couldnt pinpoint the problem....and it was driving me crazy :)

**Comment by vlaben** [comment]
No problem. All of this is because how `callExtension` works.
It simply returns string. As an example - HiveExt on server start
retrieves data from DB and creates file with output.
That file is loaded and compiled - huge string is converted into huge array with data :)

**Comment by vlaben** [comment]
Anyway, feel free to close this issue, if it's resolved. And once again - my apology for so late response.
